bind = 'hostname:8000'
certfile = 'ssl/signaling.crt'
keyfile = 'ssl/signaling.key'
accesslog = '/dev/null'
loglevel = 'debug'
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
