bind = '0.0.0.0:8000'
certfile = 'ssl/signaling.crt'
keyfile = 'ssl/signaling.key'
accesslog = '/dev/stdout'
loglevel = 'error'
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
