FROM debian:buster

USER root

RUN apt-get -y update ; \
    apt-get -y install nginx

WORKDIR /home/

COPY front-end/ ./

COPY nginx.conf /etc/nginx/conf.d/

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]

# CMD ["bash"]