FROM debian:buster

USER root

RUN apt-get -y update ; \
    apt-get -y install python3

WORKDIR /home/

COPY front-end/ ./

EXPOSE 443

CMD ["python3.7", "-m", "http.server", "443", "--bind", "127.0.0.1"]

# CMD ["bash"]