FROM python:3.8

WORKDIR /app

RUN apt-get -y update ; \
    apt-get -y install openssl

RUN mkdir ssl

RUN openssl req \
    -x509 \
    -nodes \
    -out ssl/signaling.crt \
    -keyout ssl/signaling.key \
    -subj "/C=FR/ST=PACA/L=Nice/O=42/OU=42Nice/CN=0.0.0.0"

COPY ./server/requirements.txt .

COPY ./server .

RUN pip install -r requirements.txt ; \
    pip install django-cors-headers ; \
    pip install requests

COPY init.sh /home/

EXPOSE 8000

CMD ["sh", "/home/init.sh"]
